# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Array Creation Routines</span>

<br>

To use numpy in python import it first by using the following command:

In [1]:
# import numpy
import numpy as np

<br>

There are various tools available in numpy to create an array. Following is the list of tools categories for array creation:

1. Ones and zeros
2. From existing data
3. Creating record arrays
4. Creating character arrays
5. Numerical ranges
6. Building matrices
7. The Matrix class

Major ones are 1. Ones & Zeros, 2. Existing Data and 3. Numerical Ranges

<br>

## <span style="color:#4D77CF">Ones and Zeros</span>

| Function       | Objective                                                    |
| :-------------:| ------------------------------------------------------------ |
| `empty()`      | Return a new array of given shape and type, without initializing entries. |
| `eye()`        | Return a 2-D array with ones on the diagonal and zeros elsewhere. |
| `identity()`   | Return the identity array.                                   |
| `ones()`       | Return a new array of given shape and type, filled with ones. |
| `zeros()`      | Return a new array of given shape and type, filled with zeros. |
| `full()`       | Return a new array of given shape and type, filled with *fill_value*. |

Note: `empty_like()`, `ones_like()`, `zeros_like()` and `full_like()` return an array with same shape and type as given array.

Following are the most common parameters for these methods:

| Parameter | Description                                                  |
| :-------: | ------------------------------------------------------------ |
| **Shape** | Shape of an empty array in int or tuple of int               |
| **Dtype** | Desired output data type. Optional                           |
| **Order** | 'C' for C-style row-major array, 'F' for FORTRAN style column-major array |

<br>

In [3]:
# empty()

In [4]:
## with C-style order
empty_c = np.empty([3,2], dtype = int, order='C') 
empty_c

array([[-1350281296,         486],
       [-1350281216,         486],
       [ 2020176500,   542858024]])

In [5]:
## with F-style order
empty_F = np.empty([3,2], dtype = int, order='F') 
empty_F

array([[-1462538208,           0],
       [        486,           1],
       [          0,   538976288]])

<br>

In [6]:
# ones()

In [7]:
ones_r = np.ones(5, order='F')
ones_r

array([1., 1., 1., 1., 1.])

In [8]:
ones_r_like = np.ones_like(ones_r)
ones_r_like

array([1., 1., 1., 1., 1.])

<br>

In [9]:
# zeros()

In [10]:
zeros_r = np.zeros(5)
zeros_r

array([0., 0., 0., 0., 0.])

<br>

## <span style="color:#4D77CF">From Exisiting Data</span>

|        Method         | Objective                                                    |
| :-------------------: | ------------------------------------------------------------ |
|       `array()`       | Create an array.                                             |
|      `asarray()`      | Convert the input to an array.                               |
|    `asanyarray()`     | Convert the input to an ndarray, but pass ndarray subclasses through. |
| `ascontiguousarray()` | Return a contiguous array (ndim >= 1) in memory (C order).   |
|     `asmatrix()`      | Interpret the input as a matrix.                             |
|       `copy()`        | Return an array copy of the given object.                    |
|    `frombuffer()`     | Interpret a buffer as a 1-dimensional array.                 |
|     `fromfile()`      | Construct an array from data in a text or binary file.       |
|   `fromfunction()`    | Construct an array by executing a function over each coordinate. |
|     `fromiter()`      | Create a new 1-dimensional array from an iterable object.    |
|    `fromstring()`     | A new 1-D array initialized from text data in a string.      |
|      `loadtxt()`      | Load data from a text file.                                  |

<br>

In [11]:
# array()
a = np.array([[3, 4, 5], [6, 7, 8]], np.int32)
print(a)

[[3 4 5]
 [6 7 8]]


<br>

In [12]:
# asarray()

```python
numpy.asarray(a, dtype = None, order = None)
```

| Parameter  | Objective                                              |
| :--------: | :----------------------------------------------------- |
| **a** | Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists              |
| **dtype**  | Data type of returned ndarray. Defaults to float       |
| **order**  | C (row major) or F (column major). C is default|

In [13]:
x = [1,2,3] 
a = np.asarray(x) 
print(a)

[1 2 3]


<br>

In [14]:
# frombuffer()

```python
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```

| Parameter  | Objective                                              |
| :--------: | :----------------------------------------------------- |
| **buffer** | Any object that exposes buffer interface               |
| **dtype**  | Data type of returned ndarray. Defaults to float       |
| **count**  | The number of items to read, default -1 means all data |
| **offset** | The starting position to read from. Default is 0       |

In [15]:
x = b'Hello World' 
a = np.frombuffer(x, dtype="S1") 
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [16]:
b = np.frombuffer(b'\x01\x02', dtype=np.uint8)
print(b)

[1 2]


<br>

In [17]:
# fromiter()

```python
numpy.fromiter(iterable, dtype, count = -1)
```

|  Parameter   | Objective                                              |
| :----------: | :----------------------------------------------------- |
| **iterable** | Any iterable object                                    |
|  **dtype**   | Data type of returned ndarray. Defaults to float       |
|  **count**   | The number of items to read, default -1 means all data |

In [18]:
# create list object using range function 
list_x = range(5)

# obtain iterator object from list 
it = iter(list_x)

# use iterator to create ndarray 
a = np.fromiter(it, dtype = float)
print(a)

[0. 1. 2. 3. 4.]


<br>

## <span style="color:#4D77CF">Numerical Ranges</span>

|    Methods    | Objective                                                    |
| :-----------: | ------------------------------------------------------------ |
|  `arange()`   | Return evenly spaced values within a given interval.         |
| `linspace()`  | Return evenly spaced numbers over a specified interval.      |
| `logspace()`  | Return numbers spaced evenly on a log scale.                 |
| `geomspace()` | Return numbers spaced evenly on a log scale (a geometric progression). |
| `meshgrid()`  | Return coordinate matrices from coordinate vectors.          |
|   `mgrid()`   | *nd_grid* instance which returns a dense multi-dimensional “meshgrid”. |
|   `ogrid()`   | *nd_grid* instance which returns an open multi-dimensional “meshgrid”. |

<br>

In [19]:
# arrange()

```python
numpy.arange(start, stop, step, dtype)
```

| Parameter | Description                                                  |
| :-------: | :----------------------------------------------------------- |
| **start** | The start of an interval. If omitted, defaults to 0          |
| **stop**  | The end of an interval (not including this number)           |
| **step**  | Spacing between values, default is 1                         |
| **dtype** | Data type of resulting ndarray. If not given, data type of input is used |

In [23]:
x_int = np.arange(5)
x_int

array([0, 1, 2, 3, 4])

In [24]:
## dtype set 
x_float = np.arange(5, dtype=float)
x_float

array([0., 1., 2., 3., 4.])

In [25]:
## start and stop parameters set
x_step = np.arange(10,20,2)
x_step

array([10, 12, 14, 16, 18])

<br>

In [2]:
# linspace()

```python
numpy.linspace(start, stop, num, endpoint, retstep, dtype)
```

|  Parameter   | Description                                                  |
| :----------: | :----------------------------------------------------------- |
|  **start**   | The starting value of the sequence                           |
|   **stop**   | The end value of the sequence, included in the sequence if endpoint set to true |
|   **num**    | The number of evenly spaced samples to be generated. Default is 50 |
| **endpoint** | True by default, hence the stop value is included in the sequence. If false, it is not included |
| **retstep**  | If true, returns samples and step between the consecutive numbers |
|  **dtype**   | Data type of output **ndarray**                              |

In [4]:
x = np.linspace(10,20,5) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [5]:
# endpoint set to false 

x = np.linspace(10,20, 5, endpoint = False) 
print(x)

[10. 12. 14. 16. 18.]


In [12]:
# find retstep value

x = np.linspace(1,2,5, retstep = True) 
print("output is  : ", x)
print("retspet is : ", x[1])

output is  :  (array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
retspet is :  0.25


In [13]:
# logspace()

```python
numpy.logspace(start, stop, num, endpoint, base, dtype)
```

|  Parameter   | Description                                                  |
| :----------: | :----------------------------------------------------------- |
|  **start**   | The starting point of the sequence is basestart              |
|   **stop**   | The final value of sequence is basestop                      |
|   **num**    | The number of values between the range. Default is 50        |
| **endpoint** | If true, stop is the last value in the range                 |
|   **base**   | Base of log space, default is 10                             |
|  **dtype**   | Data type of output array. If not given, it depends upon other input arguments |

In [15]:
# default base is 10 

x = np.logspace(1.0, 2.0, num = 10) 
print(x)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [16]:
# set base of log space to 2 

x = np.logspace(1,10,num = 10, base = 2) 
print(x)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
