# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Indexing & Slicing</span>

To use numpy in python import it first by using the following command:

In [1]:
# import numpy
import numpy as np

<br>

Items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

## <span style="color:#4D77CF"> Basic Slicing </span>

- It is an extention of Python's slicing concept.
- A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function.
- Python slice object is passed to an array to slice the array.

In [2]:
# create an array

# one dimentional array
a_1d = np.arange(10)
print('1D array: ')
print(a_1d)

print('\n')

# multi-dimentional array
a_nd = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('nD array: ')
print(a_nd)

1D array: 
[0 1 2 3 4 5 6 7 8 9]


nD array: 
[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [3]:
# create slice object
s = slice(2,7,2) 

# pass slice object to an array
print('1D array sliced: ', a_1d[s])
print('nD array sliced: ', a_nd[s])

1D array sliced:  [2 4 6]
nD array sliced:  [[4 5 6]]


The same result can also be obtained by giving the slicing parameters separated by a colon : (start:stop:step) directly to the ndarray object.

In [4]:
print('1D array sliced: ', a_1d[2:7:2])
print('nD array sliced: ', a_nd[2:7:2])

1D array sliced:  [2 4 6]
nD array sliced:  [[4 5 6]]


If only one parameter is put, a single item corresponding to the index will be returned.

In [5]:
# slice single item
print('1D array sliced: ', a_1d[0])
print('nD array sliced: ', a_nd[0])

1D array sliced:  0
nD array sliced:  [1 2 3]


If a : is inserted in front of it, all items from that index onwards will be extracted.

In [6]:
# slice items starting from index
print('1D array sliced: ', a_1d[2:])
print('nD array sliced: ', a_nd[2:])

1D array sliced:  [2 3 4 5 6 7 8 9]
nD array sliced:  [[4 5 6]]


If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [7]:
# slice items between indexes
print(a_nd[1:2])

[[3 4 5]]


<br>

Using ellipsis (…) for basic slicing.

- Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. 
- If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

<div style="text-align:center"><img src="./img/slicing.png" width=70% height=70%/></div>

In [8]:
# slice all items from the second column 
print(a_nd[...,1]) 

[2 4 5]


In [9]:
# slice all items from the second row 
print(a_nd[1,...])

[3 4 5]


In [10]:
# slice all items from column 1 onwards
print(a_nd[...,1:])

[[2 3]
 [4 5]
 [5 6]]


<br>

## <span style="color:#4D77CF"> Advanced Indexing </span>

Advanced indexing is triggered when the selection object, obj, is a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool). 

Advanced indexing always returns a copy of the data. As against this, the slicing only presents a view.

There are two types of advanced indexing 
1. Integer 
2. Boolean.

### <span style="color:#4D77CF"> Integer Indexing </span>

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indexes into that dimension.

When the index consists of as many integer arrays as the dimensions of the target ndarray, it becomes straightforward.

In [11]:
# create an array
x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
# using list of index values for [row],[col]
y = x[[0,1,2], [0,1,0]] 
print(y)

print("\nThe selection includes elements at (0,0), (1,1) and (2,0) from the first array.")

[1 4 5]

The selection includes elements at (0,0), (1,1) and (2,0) from the first array.


<br>

Using integer indexing for multiple rows and columns.

In [13]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
# using index array for indexing
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
print(y)

[[ 0  2]
 [ 9 11]]


<br>

Advanced and basic indexing can be combined by using one slice (:) or ellipsis (…) with an index array.

In [15]:
# slicing 
z = x[1:4,1:3]
print(z)

[[ 4  5]
 [ 7  8]
 [10 11]]


In [16]:
# using advanced index for column 
y = x[1:4,[1,2]] 
print(y)

[[ 4  5]
 [ 7  8]
 [10 11]]


<br>

### <span style="color:#4D77CF"> Boolean Array Indexing </span>

This type of advanced indexing is used when the resultant object is meant to be the result of Boolean operations, such as comparison operators.

In [17]:
# print the items greater than 5 
print(x[x > 5])

[ 6  7  8  9 10 11]


In [19]:
# omit NaN (Not a Number) elements by using ~ (complement operator)
a_nan = np.array([np.nan, 1,2,np.nan,3,4,5])
print(a_nan[~np.isnan(a_nan)])

[1. 2. 3. 4. 5.]
