# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Iteration</span>

To use numpy in python import it first by using the following command:

In [2]:
# import numpy
import numpy as np

<br>

To iterate overa an array `for loop` and `nditer()` are used. `for loop` is convinient to use while iterating over an 1D array but when it comes to `multi-dimension array` `nested for loop` is required thus `nditer()` is better option for iterating over an array.

## Iterating a One-dimensional Array

### For Loop

In [18]:
a = np.arange(12)

for cell in a:
    print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

The `end` specifies the character that needs to be printed after printing the value. By default, it prints a new line character.

While Loop

In [19]:
i = 0
while a[i] < a.size:
    print(a[i])
    i = i+1
    if(i==a.size):
        break

0
1
2
3
4
5
6
7
8
9
10
11


## Iterating a Two-dimensional Array

Simple for loop will only be able to iterate a row.

In [21]:
a_2d = np.arange(12).reshape(4,3)

for row in a_2d:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


To iterate each cell in the two-dimensional array, nest the for loop.

In [22]:
for row in a_2d:
    for cell in row:
        print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

`flatten()` function that flattens the two-dimensional array into a one-dimensional array

In [23]:
for cell in a_2d.flatten():
        print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

<br>

## Nditer Object

NumPy provides a multi-dimensional iterator object called `nditer` to iterate the elements of an array. 

```python
numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
```

|   Parameter    | Description                                                  |
| :------------: | :----------------------------------------------------------- |
|     **op**     | The array(s) to iterate over.                                |
|   **flags**    | Flags to control the behavior of the iterator.               |
|  **op_flags**  | This is a list of flags for each operand. At minimum, one of `readonly`, `readwrite`, or `writeonly` must be specified. |
| **op_dtypes**  | The required data type(s) of the operands. If copying or buffering is enabled, the data will be converted to/from their original types. |
|   **order**    | Controls the iteration order. <br />1. ‘C’ means C order, <br />2. F’ means Fortran order, <br />3. ‘A’ means ‘F’ order if all the arrays are Fortran contiguous, ‘C’ order otherwise, and <br />4. ‘K’ means as close to the order the array elements appear in memory as possible. |
|  **casting**   | Controls what kind of data casting may occur when making a copy or buffering. Setting this to ‘unsafe’ is not recommended, as it can adversely affect accumulations. |
|  **op_axes**   | If provided, is a list of ints or None for each operands. The list of axes for an operand is a mapping from the dimensions of the iterator to the dimensions of the operand. |
| **itershape**  | The desired shape of the iterator. This allows `allocate` operands with a dimension mapped by op_axes not corresponding to a dimension of a different operand to get a value not equal to 1 for that dimension. |
| **buffersize** | When buffering is enabled, controls the size of the temporary buffers. Set to 0 for the default value. |



In [26]:
for cell in np.nditer(a_2d):
    print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

*Difference between C order and F order:*
- C Order: elements are traversed in the array horizontally. 
- F Order: elements are traversed in the array vertically.

In [27]:
# Output with C order
for cell in np.nditer(a_2d, order='C'):
    print(cell, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [29]:
# Output with F order
for cell in np.nditer(a_2d, order='F'):
    print(cell, end=' ')

0 3 6 9 1 4 7 10 2 5 8 11 

By default, `nditer` follows the order ‘k’ which means that it follows an order to match the memory layout of the array. This default setting allows it to access the elements in the least possible time.

### Modifying NumPy Arrays

- `Nditer` treats the elements of the array as `read-only`. So, modifying values gives an error.
- To modify the array while iterating, use the op_flags parameter.

In [32]:
for cell in np.nditer(a_2d, op_flags=['readwrite']):
    cell[...] =cell*2
a_2d

array([[ 0,  8, 16],
       [24, 32, 40],
       [48, 56, 64],
       [72, 80, 88]])

### Iterating Two Arrays Simultaneously

To iterate two arrays simultaneously, pass two arrays to the nditer object.

In [33]:
s = np.arange(3)

In [34]:
for a,s in np.nditer([a_2d,s]):
    print(a, s)

0 0
8 1
16 2
24 0
32 1
40 2
48 0
56 1
64 2
72 0
80 1
88 2
