# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Array Manipulation</span>

To use numpy in python import it first by using the following command:

In [1]:
# import numpy
import numpy as np

<br>

## Changing Shape

| Operation | Description                                              |
| :-------: | :------------------------------------------------------- |
|  reshape  | Gives a new shape to an array without changing its data  |
|   flat    | A 1-D iterator over the array                            |
|  flatten  | Returns a copy of the array collapsed into one dimension |
|   ravel   | Returns a contiguous flattened array                     |

 ### reshape

This function gives a new shape to an array without changing the data.

```python
numpy.reshape(arr, newshape, order')
```

|  Parameter   | Description                                                  |
| :----------: | :----------------------------------------------------------- |
|   arr    | Array to be reshaped                                         |
| newshape | int or tuple of int. New shape should be compatible to the original shape |
|  order   | 'C' for C style, 'F' for Fortran style, 'A' means Fortran like order if an array is stored in Fortran-like contiguous memory, C style otherwise |

In [2]:
# create an array
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
# modified array
b = a.reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

### flat

This function returns a 1-D iterator over the array.

In [4]:
# returns element corresponding to index in flattened array 
b.flat[:]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
# index specific element from flattened array
b.flat[5]

5

### flatten

This function returns a copy of an array collapsed into one dimension. The function takes the following parameters.

In [6]:
# flatten array without order
b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
# flatten array in F-style orde
b.flatten(order = 'F')

array([0, 2, 4, 6, 1, 3, 5, 7])

### ravel

This function returns a flattened one-dimensional array. A copy is made only if needed. The returned array will have the same type as that of the input array.

```python
numpy.ravel(a, order)
```

In [8]:
# applying ravel without order
b.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
# applyting ravel in F-style ordering
b.ravel(order='F') 

array([0, 2, 4, 6, 1, 3, 5, 7])

<br>

## Transpose Operations

| Operation | Description                           |
| :-------: | :------------------------------------ |
| transpose | Permutes the dimensions of an array   |
| ndarray.T | Same as self.transpose()              |
| rollaxis  | Rolls the specified axis backwards    |
| swapaxes  | Interchanges the two axes of an array |

### transpose

This function permutes the dimension of the given array. It returns a view wherever possible.

```python
numpy.transpose(arr, axes)
```

|  Parameter   | Description                                                  |
| :----------: | :----------------------------------------------------------- |
|   arr    | Array to be transposed                                         |
| axes | List of ints, corresponding to the dimensions. By default, the dimensions are reversed |

In [10]:
np.transpose(b)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

### ndarray.T

This function belongs to ndarray class. It behaves similar to numpy.transpose.

In [11]:
b.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

### rollaxis

This function rolls the specified axis backwards, until it lies in a specified position.

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|    arr    | Input array                                                  |
|   axis    | Axis to roll backwards. The position of the other axes do not change relative to one another |
|   start   | Zero by default leading to the complete roll. Rolls until it reaches the specified position |

In [12]:
# create a 3D array
c = np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
# to roll axis-2 to axis-0 (along width to along depth) 
np.rollaxis(c,2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [14]:
# to roll axis 0 to 1 (along width to height) 
np.rollaxis(c,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

### swapaxis

This function interchanges the two axes of an array. For NumPy versions after 1.10, a view of the swapped array is returned. 

```python
numpy.swapaxes(arr, axis1, axis2)
```

| Operation | Description                              |
| :-------: | :--------------------------------------- |
|    arr    | Input array whose axes are to be swapped |
|   axis1   | An int corresponding to the first axis   |
|   axis2   | An int corresponding to the second axis  |

In [15]:
# to swap numbers between axis 0 (along depth) and axis 2 (along width)
np.swapaxes(c, 2, 0)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

<br>

## Changing Dimensions

|  Operation   | Description                                                  |
| :----------: | ------------------------------------------------------------ |
|  broadcast   | Produces an object that mimics broadcasting                  |
| broadcast_to | Broadcasts an array to a new shape                           |
| expand_dims  | Expands the shape of an array                                |
|   squeeze    | Removes single-dimensional entries from the shape of an array |

### broadcast

This function mimics the broadcasting mechanism. It returns an object that encapsulates the result of broadcasting one array against the other.

In [16]:
# create two arrays
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  

print('array x is:\n' , x)
print('\n')
print('array y is:\n' , y)

array x is:
 [[1]
 [2]
 [3]]


array y is:
 [4 5 6]


In [17]:
# create a broadcast object
bcast_xy = np.broadcast(x,y)
bcast_xy

It has an iterator property, a tuple of iterators along self's "components." 

In [18]:
# shape of the broadcast object
bcast_xy.shape

(3, 3)

In [19]:
# broadcast x against y:
r,c = bcast_xy.iters

In [20]:
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))

1 4
1 5
1 6
2 4


In [21]:
# Add x and y manually using broadcast:
bcast_xy = np.broadcast(x,y) 
bcast_man = np.empty(bcast_xy.shape)
bcast_man.flat = [u + v for (u, v) in bcast_xy]
bcast_man

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [22]:
# summation of x and y
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### broadcast_to

This function broadcasts an array to a new shape. It returns a read-only view on the original array. It is typically not contiguous. The function may throw ValueError if the new shape does not comply with NumPy's broadcasting rules.

```python
numpy.broadcast_to(array, shape, subok)
```

In [23]:
# creating an array of (1,4) dim
d = np.arange(4).reshape(1,4)
d

array([[0, 1, 2, 3]])

In [24]:
# broadcasting (1,4) dim array to (4,4) dim
np.broadcast_to(d,(4,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

### expand_dims

This function expands the array by inserting a new axis at the specified position. 

```python
numpy.expand_dims(arr, axis)
```

| Operation | Description                            |
| :-------: | :------------------------------------- |
|    arr    | Input array                            |
|   axis    | Position where new axis to be inserted |

In [25]:
# create 2D array
x = np.array(([1,2],[3,4])) 
x

array([[1, 2],
       [3, 4]])

In [26]:
# increase dimension of array x
y = np.expand_dims(x, axis = 0) 
y

array([[[1, 2],
        [3, 4]]])

In [27]:
# Dimension and shape of x and y arrays
print('Dimensions of x and y array are: ', x.ndim, " and ", y.ndim )
print('Shape of x and y array are: ', x.shape, " and ", y.shape )

Dimensions of x and y array are:  2  and  3
Shape of x and y array are:  (2, 2)  and  (1, 2, 2)


In [28]:
# insert axis at position 1 
y = np.expand_dims(x, axis = 1) 
y

array([[[1, 2]],

       [[3, 4]]])

In [29]:
# Dimension and shape of x and y arrays
print('Dimensions of x and y array are: ', x.ndim, " and ", y.ndim )
print('Shape of x and y array are: ', x.shape, " and ", y.shape )

Dimensions of x and y array are:  2  and  3
Shape of x and y array are:  (2, 2)  and  (2, 1, 2)


### squeeze

This function removes one-dimensional entry from the shape of the given array.

```python
numpy.squeeze(arr, axis)
```

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|    arr    | Input array                                                  |
|   axis    | int or tuple of int. selects a subset of single dimensional entries in the shape |

In [30]:
y

array([[[1, 2]],

       [[3, 4]]])

In [31]:
# squeeze y to remove 1D entry from the shape
z = np.squeeze(y)
z

array([[1, 2],
       [3, 4]])

In [32]:
# Dimension and shape of y and z arrays
print('Dimensions of y and z array are: ', y.ndim, " and ", z.ndim )
print('Shape of y and z array are: ', y.shape, " and ", z.shape )

Dimensions of y and z array are:  3  and  2
Shape of y and z array are:  (2, 1, 2)  and  (2, 2)


<br>

<br>

## Joining Arrays

| Operation   | Description                                          |
| :---------- | :--------------------------------------------------- |
| concatenate | Joins a sequence of arrays along an existing axis    |
| stack       | Joins a sequence of arrays along a new axis          |
| hstack      | Stacks arrays in sequence horizontally (column wise) |
| vstack      | Stacks arrays in sequence vertically (row wise)      |

### concatenate

Concatenation refers to joining. This function is used to join two or more arrays of the same shape along a specified axis.

```python
numpy.concatenate((a1, a2, ...), axis)
```

| Operation | Description                                             |
| :-------: | :------------------------------------------------------ |
|  a1,a2..  | Sequence of arrays of the same type                     |
|   axis    | Axis along which arrays have to be joined. Default is 0 |

In [33]:
# create arrays of same dimensions
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]])

In [34]:
a

array([[1, 2],
       [3, 4]])

In [35]:
b

array([[5, 6],
       [7, 8]])

In [36]:
# Dimension and shape of y and z arrays
print('Dimensions of a and b array are: ', a.ndim, " and ", b.ndim )
print('Shape of a and b array are: ', a.shape, " and ", b.shape )

Dimensions of a and b array are:  2  and  2
Shape of a and b array are:  (2, 2)  and  (2, 2)


In [37]:
# concatenate both arrays on axis=0
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
# concatenate both arrays on axis=1
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### stack

This function joins the sequence of arrays along a new axis.

```python
numpy.stack(arrays, axis)
```

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|  arrays   | Sequence of arrays of the same shape                         |
|   axis    | Axis in the resultant array along which the input arrays are stacked |

In [39]:
# Stack the two arrays along axis=0
np.stack((a,b),0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
# Stack the two arrays along axis=1
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

Variants of numpy.stack function to stack so as to make a single array horizontally.

### hstack

In [41]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### vstack

Variants of numpy.stack function to stack so as to make a single array vertically.

In [42]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

<br>

## Splitting Arrays

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|   split   | Splits an array into multiple sub-arrays                     |
|  hsplit   | Splits an array into multiple sub-arrays horizontally (column-wise) |
|  vsplit   | Splits an array into multiple sub-arrays vertically (row-wise) |

### split

This function divides the array into subarrays along a specified axis. 

```python
numpy.split(ary, indices_or_sections, axis)
```

|      Operation      | Description                                                  |
| :-----------------: | :----------------------------------------------------------- |
|         ary         | Input array to be split                                      |
| indices_or_sections | Can be an integer, indicating the number of equal sized subarrays to be created from the input array. If this parameter is a 1-D array, the entries indicate the points at which a new subarray is to be created. |
|        axis         | Default is 0                                                 |



In [43]:
# create an array
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
# split array a in 3 equal-sized subarrays
np.split(a,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [45]:
# split the array at positions indicated in 1-D array
np.split(a, [5,8])

[array([0, 1, 2, 3, 4]), array([5, 6, 7]), array([8])]

### hsplit

Special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array

In [46]:
# create 2D array
a = np.arange(16).reshape(4,4) 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
# hrizontally split array into two
np.hsplit(a,2) 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### vsplit

Special case of split() function where axis is 1 indicating a horizontal split regardless of the dimension of the input array

Note: Doesn't work for 1D array

In [48]:
# create 2D array
a = np.arange(16).reshape(4,4) 
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
# vertically split array into two
np.vsplit(a,2) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

<br>

## Adding / Removing Elements

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|  resize   | Returns a new array with the specified shape                 |
|  append   | Appends the values to the end of an array                    |
|  insert   | Inserts the values along the given axis before the given indices |
|  delete   | Returns a new array with sub-arrays along an axis deleted    |
|  unique   | Finds the unique elements of an array                        |

### resize

This function returns a new array with the specified size. If the new size is greater than the original, the repeated copies of entries in the original are contained.

```python
numpy.resize(arr, shape)
```

| Operation | Description                      |
| :-------: | :------------------------------- |
|    arr    | Input array to be resized        |
|   shape   | New shape of the resulting array |

In [50]:
# create 2D array
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
# resize array a into 3x2
b = np.resize(a, (3,2)) 
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
# shape of both a and b array
print('Shape of array a: ', a.shape)
print('Shape of array b: ', b.shape)

Shape of array a:  (2, 3)
Shape of array b:  (3, 2)


### append

This function adds values at the end of an input array. The append operation is not inplace, a new array is allocated. Also the dimensions of the input arrays must match otherwise ValueError will be generated.

```python
numpy.append(arr, values, axis)
```

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|    arr    | Input array                                                  |
|  values   | To be appended to arr. It must be of the same shape as of arr (excluding axis of appending) |
|   axis    | The axis along which append operation is to be done. If not given, both parameters are flattened |

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
# append elements to array a
np.append(a, [7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# append elements along axis=0
np.append(a, [[7,8,9]],axis = 0) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note: Must enter elements equal to size of columns

In [56]:
# append elements along axis=1
np.append(a, [[7,8,9],[10,11,12]],axis = 1) 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Note: Must enter list of elements equal to size of rows

### insert

This function inserts values in the input array along the given axis and before the given index. If the type of values is converted to be inserted, it is different from the input array. Insertion is not done in place and the function returns a new array. Also, if the axis is not mentioned, the input array is flattened.

```python
numpy.insert(arr, obj, values, axis)
```

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|    arr    | Input array                                                  |
|    obj    | The index before which insertion is to be made               |
|  values   | The array of values to be inserted                           |
|   axis    | The axis along which to insert. If not given, the input array is flattened |

In [57]:
# create 3D array
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
# without axis param, input array is flattened before insertion
np.insert(a,3,[11,12]) 

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [59]:
# instering aLong axis = 0
np.insert(a,1,[11],axis = 0) 

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [60]:
# instering aLong axis = 1
np.insert(a,1,[11],axis = 1) 

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

### delete

This function returns a new array with the specified subarray deleted from the input array. As in case of insert() function, if the axis parameter is not used, the input array is flattened. 

```python
numpy.delete(arr, obj, axis)
```

| Operation | Description                                                  |
| :-------: | :----------------------------------------------------------- |
|    arr    | Input array                                                  |
|    obj    | Can be a slice, an integer or array of integers, indicating the subarray to be deleted from the input array |
|   axis    | The axis along which to delete the given subarray. If not given, arr is flattened |

In [61]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
# without axis param, input array is flattened before insertion
np.delete(a,3) 

array([1, 2, 3, 5, 6])

In [63]:
# delete along axis = 0
np.delete(a,1,axis = 0) 

array([[1, 2],
       [5, 6]])

In [64]:
# delete along axis = 1
np.delete(a,1,axis = 1) 

array([[1],
       [3],
       [5]])

In [65]:
# slice containing alternate values from array deleted
x = np.array([1,2,3,4,5,6,7,8,9,10]) 
np.delete(x, np.s_[::2])

array([ 2,  4,  6,  8, 10])

### unique

This function returns an array of unique elements in the input array. The function can be able to return a tuple of array of unique vales and an array of associated indices.

Returned array are ordered.

```python
numpy.unique(arr, return_index, return_inverse, return_counts)
```

|   Operation    | Description                                                  |
| :------------: | :----------------------------------------------------------- |
|      arr       | The input array. Will be flattened if not 1-D array          |
|  return_index  | If True, returns the indices of elements in the input array  |
| return_inverse | If True, returns the indices of unique array, which can be used to reconstruct the input array |
| return_counts  | If True, returns the number of times the element in unique array appears in the original array |

In [66]:
# create an array with duplicate elements
x = np.array([5,2,6,2,7,5,6,8,2,9]) 
x

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [67]:
# unique values of array x
np.unique(x)

array([2, 5, 6, 7, 8, 9])

In [68]:
# Unique array (u) and first index of each unique element in x (v)
u, v = np.unique(x, return_index=True)
print('Unique array u from x            : ', u)
print('Unique elements first index in x : ', v)

Unique array u from x            :  [2 5 6 7 8 9]
Unique elements first index in x :  [1 0 2 4 7 9]


In [69]:
# Unique array (u) and index of each element in x in regards of unique array u
u,v = np.unique(x,return_inverse = True) 
print('Unique array u from x              : ', u)
print('Indices of unique array matching x : ', v)

Unique array u from x              :  [2 5 6 7 8 9]
Indices of unique array matching x :  [1 0 2 0 3 1 2 4 0 5]


In [70]:
# reconstruct the original array using indices
u[v]

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [71]:
# unique array and return count of unique elements in x
u,v = np.unique(x,return_counts = True) 
print('Unique array u from x             : ', u)
print('Count of each unique element in x : ', v)

Unique array u from x             :  [2 5 6 7 8 9]
Count of each unique element in x :  [3 2 2 1 1 1]
