# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Mathematical Functions</span>

To use numpy in python import it first by using the following command:

In [2]:
# import numpy
import numpy as np

## Mathematical Functions

Numpy is written purely in C language. Hence, it’s mathematical functions are closely associated with functions present is math.h library in C.

### Arithmatic Functions

| Function                | Description                                                                                                             |
|-------------------------|-------------------------------------------------------------------------------------------------------------------------|
| add(arr1, arr2,..)      | Add arrays element wise                                                                                                 |
| divide(arr1,arr2)       | Divide arrays element wise                                                                                              |
| divmod(arr1,arr2)       | Returns remainder and quotient after division elementwise                                                               |
| float_power(arr1,arr2)  | Return the first array with its each of its elements raised to the power of elements in the second array (elementwise)  |
| floor_divide(arr1,arr2) | Returns floor after dividing an array element wise                                                                      |
| fmod(arr1,arr2)         | Returns floor of the remainder after division elementwise                                                               |
| mod(arr1,arr2)          | Returns remainder after division elementwise                                                                            |
| multiply(arr1,arr2,…)   | Multiply arrays element wise                                                                                            |
| negative(arr)           | Returns numerical negative of elements of an array                                                                      |
| power(arr1,arr2)        | Return the first array with its each of its elements raised to the power of elements in the second array (element wise) |
| reciprocal(arr)         | Returns reciprocal of elements of the argument array                                                                    |
| remainder(arr1,arr2)    | Returns remainder after division elementwise                                                                            |
| subtract(arr1,arr2,…)   | Subtract arrays element wise                                                                                            |
| true_divide(arr1,arr2)  | Returns true_divide of an array element wise                                                                            |

In [36]:
# create arrays
a = np.array([10,20,30])
b= np.array([1,2,3])

In [39]:
# some important arithmatic functions - PART 1
print("addition of a and b       : ",np.add(a,b))
print("multiplication of a and b : ",np.multiply(a,b))
print("subtraction of a and b    : ",np.subtract(a,b))
print("a raised to power b is    : ",np.power(a,b))

addition of a and b       :  [11 22 33]
multiplication of a and b :  [10 40 90]
subtraction of a and b    :  [ 9 18 27]
a raised to power b is    :  [   10   400 27000]


In [40]:
# some important arithmatic functions - PART 2
print("division of a and b               : ", np.divide(a,b))
print("true division of a                : ", np.true_divide(a,b))
print("floor_division of a and b         : ", np.floor_divide(a,b))
print("float_power of a raised to b      : ", np.float_power(a,b))
print("fmod of a and b                   : ", np.fmod(a,b))
print("mod of a and b                    : ", np.mod(a,b))
print("quotient and remainder of a and b : ", np.divmod(a,b))
print("remainders when a/b               : ", np.remainder(a,b))

division of a and b               :  [10. 10. 10.]
true division of a                :  [10. 10. 10.]
floor_division of a and b         :  [10 10 10]
float_power of a raised to b      :  [1.0e+01 4.0e+02 2.7e+04]
fmod of a and b                   :  [0 0 0]
mod of a and b                    :  [0 0 0]
quotient and remainder of a and b :  (array([10, 10, 10], dtype=int32), array([0, 0, 0], dtype=int32))
remainders when a/b               :  [0 0 0]


### Trigonometric Functions

| Function                  | Description                                                                     |
|---------------------------|---------------------------------------------------------------------------------|
| arccos(arr)               | Returns trigonometric inverse cosine element wise                               |
| arcsin(arr)               | Returns trigonometric inverse sine element wise                                 |
| arctan(arr)               | Returns trigonometric inverse tan element wise                                  |
| cos(arr)                  | Returns trigonometric cos element wise                                          |
| degrees(arr) rad2deg(arr) | Covert input angles from radians to degrees                                     |
| hypot(a,b)                | Returns hypotenuse of a right triangle with perpendicular and base as arguments |
| radians(arr) deg2rad(arr) | Covert input angles from degrees to radians                                     |
| sin(arr)                  | Returns trigonometric sine element wise                                         |
| tan(arr)                  | Returns trigonometric tan element wise                                          |

In [48]:
# create an input array angles
angles = np.array([0,np.pi/2, np.pi])
print(angles)

[0.         1.57079633 3.14159265]


In [43]:
sin_angles = np.sin(angles)
print("sin of angles:",sin_angles)

sin of angles: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [44]:
cosine_angles = np.cos(angles)
print("cosine of angles:",cosine_angles)

cosine of angles: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [45]:
tan_angles = np.tan(angles)
print("tan of angles:",tan_angles)

tan of angles: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [46]:
rad2degree = np.degrees(angles)
print("angles in radians",rad2degree)

angles in radians [  0.  90. 180.]


### Logarithmic and Exponential Functions

| Function        | Description                                                             |
|-----------------|-------------------------------------------------------------------------|
| exp(arr)        | Returns exponential of an input array element wise                      |
| exp2(arr)       | Returns exponential 2**x of all elements in an array                    |
| expm1(arr)      | Returns exponential exp(x)-1 of an input array element wise             |
| log(arr)        | Returns natural log of an input array element wise                      |
| log10(arr)      | Returns log base 10 of an input array element wise                      |
| log2(arr)       | Returns log base 2 of an input array element wise                       |
| logaddexp(arr)  | Returns logarithm of the sum of exponentiations of all inputs           |
| logaddexp2(arr) | Returns logarithm of the sum of exponentiations of the inputs in base 2 |

In [49]:
# create an array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [50]:
a_log = np.log(a)
print("log of input array a is:",a_log)

log of input array a is: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [51]:
a_exp = np.exp(a)
print("exponent of input array a is:",a_exp)

exponent of input array a is: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Rounding Functions

| Function            | Description                                                              |
|---------------------|--------------------------------------------------------------------------|
| around(arr,decimal) | Rounds the elements of an input array upto given decimal places          |
| ceil(arr)           | Returns ceiling of input array element wise                              |
| fix(arr)            | Round the elements of an input array to the nearest integer towards zero |
| floor(arr)          | Returns floor of input array element wise                                |
| rint(arr)           | Round the elements of an input array to the nearest integer towards zero |
| round_(arr,decimal) | Rounds the elements of an input array upto given decimal places          |
| trunc(arr)          | Return the truncated value of an input array element wise                |

In [53]:
# create an array with decimal values
a = np.array([1.23,4.165,3.8245])
a

array([1.23  , 4.165 , 3.8245])

In [54]:
# round decimal values in array to 2 decimal
rounded_a = np.round_(a,2)
print(rounded_a)

[1.23 4.16 3.82]


In [56]:
# floor value for decimal value in array
np.floor(a)

array([1., 4., 3.])

In [57]:
# ceiling value for decimal value in array
np.ceil(a)

array([2., 5., 4.])

### Miscellaneous Functions

| Function                    | Description                                                 |
|-----------------------------|-------------------------------------------------------------|
| absolute(arr)               | Returns absolute value each element in an input array       |
| cbrt(arr)                   | Returns cube root of an input array element wise            |
| clip(arr, arr_min, arr_max) | Limits the values in an input array                         |
| convolve(arr, v)            | Returns linear convolution of two one-dimensional sequences |
| interp(arr, xp, fp)         | Calculates one-dimensional linear interpolation             |
| maximum(arr1,arr2,…)        | Returns element wise maximum of the input arrays            |
| minimum(arr1,arr2,…)        | Returns element wise minimum of the input arrays            |
| sqrt(arr)                   | Returns the square root of an input array element wise      |

In [58]:
# create arrays
a = [1,2,3] 
b = [3,1,2] 

In [59]:
# return maximum elemenwise in both array a & b
maximum_elementwise = np.maximum(a,b)
print("maxima are:",maximum_elementwise)

maxima are: [3 2 3]


In [61]:
# clipping an array between max_limit and min_limit 
limiting_a = np.clip(a,0,2)
print("limiting a between 0 and 2:",limiting_a)

limiting a between 0 and 2: [1 2 2]
