# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Statistical Functions</span>

To use numpy in python import it first by using the following command:

In [2]:
# import numpy
import numpy as np

| Functions          | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| all()              | Test whether all array elements along a given axis evaluate to True. |
| amin(), amax()     | Returns minimum and maximum elements in the array along the specified axis respectively. |
| any()              | Test whether any array element along a given axis evaluates to True. |
| argmin(), argmax() | Returns the indices of the minimum / maximum values along an axis    |
| cumprod()          | Return the cumulative product of elements along a given axis.        |
| cumsum()           | Return the cumulative sum of the elements along a given axis.        |
| mean()             | Compute the arithmetic mean along the specified axis.                |
| min(), max()       | Return the minimum / maximum of an array or minimum along an axis.   |
| percentile()       | Returns nth percentile of the given data (array elements) along the specified axis.  |
| prod()             | Return the product of array elements over a given axis.              |
| ptp()              | Rturn the range of values along an axis.                             |
| sum()              | Sum of array elements over a given axis.                             |
| std()              | Compute the standard deviation along the specified axis.             |
| var()              | Compute the variance along the specified axis.                       |

In [19]:
# create an array
a = np.array([[10, 20, 30], [40, 50, 60]])
a

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# important statistical functions - PART 1
print("Mean : ", np.mean(a))
print("Std  : ", np.std(a))
print("Var  : ", np.var(a))
print("Sum  : ", np.sum(a))
print("Prod : ", np.prod(a))

Mean :  35.0
Std  :  17.07825127659933
Var  :  291.6666666666667
Sum  :  210
Prod :  720000000


In [23]:
# important statistical functions - PART 2
print("min and max along axis=0        : ", np.min(a, axis=0), '&', np.max(a, axis=0))
print("amin and amax along axis=1      : ", np.amin(a, axis=1), '   &', np.amax(a, axis=1))
print("argmin and argmax along axis=1  : ", np.argmin(a, axis=1), '     &', np.argmax(a, axis=1))

min and max along axis=0        :  [10 20 30] & [40 50 60]
amin and amax along axis=1      :  [10 40]    & [30 60]
argmin and argmax along axis=1  :  [0 0]      & [2 2]


In [28]:
# important statistical functions - PART 3
print('cumilative product along axis=1 : \n', np.cumprod(a, axis=1))
print('cumilative sum along axis=1     : \n', np.cumsum(a, axis=1))

cumilative product along axis=1 : 
 [[    10    200   6000]
 [    40   2000 120000]]
cumilative sum along axis=1     : 
 [[ 10  30  60]
 [ 40  90 150]]


In [32]:
# important statistical functions - PART 4
print("75 percentile along axis=1 : ", np.percentile(a, 75, axis=1))
print("Peek-to-peek along axis=1  : ", np.ptp(a, axis=1))

75 percentile along axis=1 :  [25. 55.]
Peek-to-peek along axis=1  :  [20 20]
