# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Sort, Search & Count</span>

To use numpy in python import it first by using the following command:

In [2]:
# import numpy
import numpy as np

<br>

## Sorting Function

- There are a wide variety of sorting functions in NumPy. 
- These sorting functions implement different sorting algorithms, each of them characterized by 
    - speed of execution
    - worst case performance
    - workspace required
    - stability

|     kind    | speed |  worst case | work space | stable |
|:-----------:|:-----:|:-----------:|:----------:|:------:|
| ‘quicksort’ |   1   |    O(n^2)   |      0     |   no   |
| ‘mergesort’ |   2   | O(n*log(n)) |    ~n/2    |   yes  |
|  ‘heapsort’ |   3   | O(n*log(n)) |      0     |   no   |

### sort()

The sort() function returns a sorted copy of the input array. 

```python
numpy.sort(a, axis, kind, order)
```

| Operation | Description                                                                                               |
|:---------:|-----------------------------------------------------------------------------------------------------------|
|     a     | Array to be sorted                                                                                        |
|    axis   | The axis along which the array is to be sorted. If none, the array is flattened, sorting on the last axis |
|    kind   | Default is quicksort                                                                                      |
|   order   | If the array contains fields, the order of fields to be sorted                                            |

In [15]:
# create simple 2D array
a = np.array([[3,7],[9,1]])

# create multiple datatype array
dt = np.dtype([('name', 'S10'),('age', int)]) 
b = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 

In [16]:
a

array([[3, 7],
       [9, 1]])

In [17]:
b

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [11]:
# sort array without axis
print(np.sort(a))

[[3 7]
 [1 9]]


In [14]:
# sort array along axis = 0
print(np.sort(a, axis=0))

[[3 1]
 [9 7]]


In [18]:
# order parameter in sort function 
print(np.sort(b, order='name'))

[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


### argsort()

- This function returns the indices of the sorted array.
- It can be performed along axis

```python

```

In [22]:
# argsort array
x = np.argsort(a)
print(x)

[[0 1]
 [1 0]]


In [23]:
# reconstruct original array in sorted order
a[x]

array([[[3, 7],
        [9, 1]],

       [[9, 1],
        [3, 7]]])

In [24]:
# construct the original array using loop
for i in x:
    print(a[i])

[[3 7]
 [9 1]]
[[9 1]
 [3 7]]


### lexsort()

- This function performs an indirect sort using a sequence of keys. 
- The keys can be seen as a column in a spreadsheet. 
- The function returns an array of indices, using which the sorted data can be obtained. 

Note: that the last key happens to be the primary key of sort.

In [28]:
p = ('raju','anil','ravi','amar') 
q = ('a1', 'b2', 'c3', 'd4') 

In [29]:
# lexsort() apply
r = np.lexsort((q,p)) 
print(r)

[3 1 0 2]


In [30]:
# use this index to get sorted data
t = [p[i] + ", " + q[i] for i in r]
print(t)

['amar, d4', 'anil, b2', 'raju, a1', 'ravi, c3']


<br>

Other sorting functions are:

| Function       | Description                                                |
|----------------|------------------------------------------------------------|
| ndarraysort()  | It is for sorting an array in place.                       |
| msort()        | It returns an array which sorted along the first axis      |
| partition()    | It returns a copy of array partition.                      |
| argpartition() | It returns the partition of an aray along a specific axis. |
| sort_compex()  | It sorts the real and imaginary parts separately.          |

## Search Function

- To determine the position of a given element or value inside an array. 
- There are functions to find the maximum, minimum, or a value satisfying a particular condition. 

### argmin() & argmax()

These two functions return the indices of minimum and maximum elements respectively along the given axis.

In [31]:
# create an array
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [35]:
# argmin and argmax function
print("argmin and argmax wihtout def axis  : ", np.argmin(a), " & ", np.argmax(a))
print("argmin and argmax along with axis=0 : ", np.argmin(a, axis=0), " & ", np.argmax(a, axis=0))
print("argmin and argmax along with axis=1 : ", np.argmin(a, axis=1), " & ", np.argmax(a, axis=1))

argmin and argmax wihtout def axis  :  5  &  7
argmin and argmax along with axis=0 :  [0 1 1]  &  [1 2 0]
argmin and argmax along with axis=1 :  [0 2 0]  &  [2 0 1]


### nanargmin() & nanargmax()

These function returns the index of the minimum and maximum elements respectively after ignoring ‘Not a Number’ (NaN) values present in the list.

In [36]:
# create an array with NaN values in it
a = np.array([[74,np.nan,59],[56,98,np.nan]])
a

array([[74., nan, 59.],
       [56., 98., nan]])

In [54]:
# nanargmin and nanargmax function
print("nanargmin and nanargmax wihtout def axis  : ", np.nanargmin(a), " & ", np.nanargmax(a))
print("nanargmin and nanargmax along with axis=0 : ", np.nanargmin(a, axis=0), " & ", np.nanargmax(a, axis=0))
print("nanargmin and nanargmax along with axis=1 : ", np.nanargmin(a, axis=1), " & ", np.nanargmax(a, axis=1))

nanargmin and nanargmax wihtout def axis  :  1  &  6
nanargmin and nanargmax along with axis=0 :  [1 0 1]  &  [2 2 0]
nanargmin and nanargmax along with axis=1 :  [1 2 2]  &  [2 1 0]


### nonzero()

This function returns the indices of non-zero elements in the input array.

In [39]:
# create an array with zero values in it
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [40]:
# apply nonzero function
print(np.nonzero(a))

(array([0, 0, 1, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 0, 2], dtype=int64))


### extract()

This function returns the elements satisfying any condition.

In [41]:
# create an array
a = np.arange(9.).reshape(3, 3) 
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
# define a condition 
condition = np.mod(a,2) == 0 

# element-wise value of condition
condition

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [49]:
# extract elements using condition
np.extract(condition, a)

array([0., 2., 4., 6., 8.])

### where()

This function returns the indices of elements in an input array where the given condition is satisfied.

In [43]:
# indices of elements > 3
b = np.where(a > 3)
b

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [44]:
# use indices to get elements satisfying the condition
a[b]

array([4., 5., 6., 7., 8.])

<br>

Other search functions are:

| Function       | Description                                                                |
|----------------|----------------------------------------------------------------------------|
| argwhere()     | It is used to group elements having non-zero indices.                      |
| flatnonzero()  | It returns a flattened array consisting of elements with non-zero indices. |
| where()        | It returns elements following a condition.                                 |
| searchsorted() | It returns indices of elements that are in sorted manner.                  |

## Count Function

To count a specific kind of value from the array list.

### count_nonzero()

- This function returns the count of all the non-zero values from the array. 
- It can apply this function along a specific axis.

In [51]:
# create an array
a = np.array([[16,0,56],[2,34,0],[90,87,0]])
a

array([[16,  0, 56],
       [ 2, 34,  0],
       [90, 87,  0]])

In [53]:
print("Count Non-Zero without def axis  : ", np.count_nonzero(a))
print("Count Non-Zero along with axis=0 : ", np.count_nonzero(a, axis=0))
print("Count Non-Zero along with axis=1 : ", np.count_nonzero(a, axis=1))

Count Non-Zero without def axis  :  6
Count Non-Zero along with axis=0 :  [3 2 1]
Count Non-Zero along with axis=1 :  [2 2 2]
