# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">View vs Copy</span>

To use numpy in python import it first by using the following command:

In [1]:
# import numpy
import numpy as np

<br>

## No copy

- When we make assignments to an array it does not create a copy of the array. 
- It actually accesses the original array through its id(). 
- The id() element is equivalent to pointers in c /c++ language. 
- They just point to the original array.

In [2]:
# declaring an array 
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# check id of array a
print(id(a))

2303288779920


In [4]:
# assign array a to another variable
b = a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# check id of array b
print(id(b))

2303288779920


In [6]:
# verify if both ID are same
print("Are both ID same? : ", (id(a) == id(b)))

Are both ID same? :  True


## View or Shallow copy

- It returns a view of the original array stored at the existing location.
- The view doesn’t have its own data or memory but uses the original array.
- The modifications reflect in both.

In [7]:
# define an array
a = np.array([20,30,50,70])
a

array([20, 30, 50, 70])

In [8]:
# create a view of array a
b = a.view()
b

array([20, 30, 50, 70])

In [9]:
# check ID of both base and view array
print('ID of base array "a" is : ' , id(a))
print('ID of view array "b" is : ', id(b))
print("Are both ID same?       : ", (id(a) == id(b)))

ID of base array "a" is :  2303413083072
ID of view array "b" is :  2303413082752
Are both ID same?       :  False


In [10]:
# change a value in base array a
a[0] = 50

print('array "a" is : ', a)
print('array "b" is : ', b)

array "a" is :  [50 30 50 70]
array "b" is :  [50 30 50 70]


In [11]:
# change a value in viewed array b
b[0] = 77

print('array "a" is : ', a)
print('array "b" is : ', b)

array "a" is :  [77 30 50 70]
array "b" is :  [77 30 50 70]


## Copy or Deep copy

- It returns a copy of the original array stored at a new location. 
- The copy doesn’t share data or memory with the original array. 
- The modifications are not reflected. 

In [12]:
# define an array
a = np.array([20,30,50,70])
a

array([20, 30, 50, 70])

In [13]:
# create a copy of array a
b = a.copy()
b

array([20, 30, 50, 70])

In [14]:
# check ID of both base and view array
print('ID of base array "a" is : ' , id(a))
print('ID of view array "b" is : ', id(b))
print("Are both ID same?       : ", (id(a) == id(b)))

ID of base array "a" is :  2303413139696
ID of view array "b" is :  2303413109664
Are both ID same?       :  False


In [15]:
# change a value in base array a
a[0] = 50

print('array "a" is : ', a)
print('array "b" is : ', b)

array "a" is :  [50 30 50 70]
array "b" is :  [20 30 50 70]


In [16]:
# change a value in viewed array b
b[0] = 77

print('array "a" is : ', a)
print('array "b" is : ', b)

array "a" is :  [50 30 50 70]
array "b" is :  [77 30 50 70]


<br>

## Views vs Copies: The main differences

Here are the main differences between views and copies:

1. Modifying the array
    - Modifying a view modifies the base (original) array, whereas modifying a copy does not modify the base array.
2. Time taken
    - Making a copy takes more time, often 1.5x-2x longer.
3. Base of the array
    - A view has the same base as its base array. A copy does not.
4. Memory
    - A view also shares memory with the base array, whereas a copy does not.
5. Indexing
    - Normal indexing returns view while fancy indexing returns copy.

|                        | View                    | Copy                            |
|------------------------|-------------------------|---------------------------------|
| Slices                 | Indexing, e.g. `a[0,:]` | Fancy indexing, e.g. `a[[0],:]` |
| Changing dtype         | `v = a.view('int16')`   | `c = a.astype(np.float32)`       |
| Converting to 1D array | `a.ravel()`             | `a.flatten()`                   |

<br>

## View Creation

There are two methods to create a view of numpy arrray:
1. Slice View : slicing the original array 
2. dtype View : changing data type original array

### Slice view

In this view creation, process involves:
1. Perform slicing of the original array
2. Address the view by offsets, strides, and counts of the original array

In [17]:
# define an array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# slicing of original array to create a view
v = a[1:10:2]
v

array([1, 3, 5, 7, 9])

### dtype view

In this method data type of the original array is changed in order to generate a view.

In [19]:
# define a view with data type
a = np.arange(10,dtype='int32')
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# chanding datatype of original array to create a view
v = a.view('int16')
v

array([0, 0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, 6, 0, 7, 0, 8, 0, 9, 0],
      dtype=int16)

## Checking if NumPy Array owns its data

use `base` method to find out whether or not an array has base array.

In [21]:
# define an array
a = np.array([59,87,64])
a

array([59, 87, 64])

In [22]:
# create view and copy of array a
v = a.view()
c = a.copy()

In [23]:
# check if view and copy has base array or not
print("View has base array : ", v.base)
print("Copy has base array : ", c.base)

View has base array :  [59 87 64]
Copy has base array :  None
