# <span style="color:#4D77CF; font-family: Helvetica; font-size: 200%; font-weight:700"> Numpy | <span style="font-size: 50%; font-weight:300">Matrix Library</span>

To use numpy in python import it first by using the following command:

In [1]:
# import numpy
import numpy as np

# import matlib from numpy
import numpy.matlib 

<br>

NumPy package contains a Matrix library `numpy.matlib`. This module has functions that return matrices instead of ndarray objects.

## matlib.empty()

This function returns a new matrix without initializing the entries.

```python
numpy.matlib.empty(shape, dtype, order)
```

| Operation | Description                                              |
|-----------|----------------------------------------------------------|
| shape     | int or tuple of int defining the shape of the new matrix |
| Dtype     | Optional. Data type of the output                        |
| order     | C or F                                                   |

In [2]:
# create 2x2 matrix filled with random data
np.matlib.empty((2,2)) 

matrix([[9.53991053e-312, 3.95252517e-323],
        [3.95252517e-323, 3.95252517e-323]])

## matlib.zeros()

This function returns the matrix filled with zeros.

In [3]:
# create 2x2 matrix filled with 0
np.matlib.zeros((2,2)) 

matrix([[0., 0.],
        [0., 0.]])

## matlib.ones()

This function returns the matrix filled with 1s.

In [4]:
# create 2x2 matrix filled with 1s
np.matlib.ones((2,2)) 

matrix([[1., 1.],
        [1., 1.]])

## matlib.eye()

This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere.

```python
numpy.matlib.eye(n, M,k, dtype)
```

| Operation | Description                                |
|-----------|--------------------------------------------|
| n         | The number of rows in the resulting matrix |
| M         | The number of columns, defaults to n       |
| k         | Index of diagonal                          |
| dtype     | Data type of the output                    |

In [5]:
np.matlib.eye(n = 3, M = 4, k = 0, dtype = float)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

## matlib.identity()

- This unction returns the Identity matrix of the given size. 
- An identity matrix is a square matrix with all diagonal elements as 1.

In [6]:
np.matlib.identity(5, dtype = float)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## matlib.rand()

This function returns a matrix of the given size filled with random values

In [7]:
np.matlib.rand(3,3)

matrix([[0.48301533, 0.0171169 , 0.21368552],
        [0.88379811, 0.53137918, 0.62794952],
        [0.07142603, 0.52360815, 0.97686049]])

<br>

## Matrix-Array Inter-Coversion

Note:  
- Matrix is always two-dimensional, whereas ndarray is an n-dimensional array. 
- Both the objects are inter-convertible.

In [8]:
# create a matrix
matrix_1 = np.matrix('1,2;3,4') 
matrix_1

matrix([[1, 2],
        [3, 4]])

<br>

Convert matrix into array:

In [9]:
array_1 = np.asarray(matrix_1)
array_1

array([[1, 2],
       [3, 4]])

<br>

Convert array into matrix:

In [10]:
matrix_2 = np.asmatrix(array_1)
matrix_2

matrix([[1, 2],
        [3, 4]])